# Generated by Django 3.0.8 on 2020-08-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedarticlemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedArticleManager',
        ),
    ]
